### ISSUE TITLE
Element with transparent background.

### ISSUE THREAD

**Issue by innor6** [FullscreenEverything/FullscreenEverything#2]
When fullscreen an element with transparent  background, the background turns black.

We can add an option for user, to dicide whether modify the element's background-color to “white” when enable fullscreen, and recover it when exit fullscreen.

**Comment by xieby1** [comment]
I add code to get color from self or parent.

**Comment by xieby1** [comment]
TODO: If the color alpha channel is not 1, color needs to be calculated carefully.

**Comment by xieby1** [comment]
https://github.com/FullscreenEverything/FullscreenEverything/commit/d3789fb92c3f6deccff6bb862bd077a82d4533ec

Transparent color problem solution:

When entering fullscreen

* backup target element's background color.
* traverse all parent elements of the target element, and calculate the color.

When exiting from fullscreen

* restore target element's background color

I add a simple test page in `test/color_alpha.html`.
